name = "hugo-theme-fs"
license = "MIT"
licenselink = "https://github.com/OctopusET/hugo-theme-fs/blob/master/LICENSE"
description = "A minimalist monospace blog theme inspired by Fabien Sanglard's website"
min_version = "0.91.0"

[author]
  name = "Sungjoon Moon"
  homepage = "https://seoulsaram.org"
